### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by tsjuusmei** [lars-ruijs/real-time-web-2021#1]
Repo ziet er clean en nice uit. Description is aanwezig, ook een concept beschrijving en wat je gaat maken én de livelink is aanwezig, chill.

Dataflow diagram, installation guide en concepten zijn aanwezig, het enige wat ik hier mis is een API uitleg.

Het diagram is erg uitgebreid en overzichtelijk, nice! Hier worden de socket events en server events mooi naast elkaar gezet en zo wordt het een mooi overzichtje.

**Comment by lars-ruijs** [comment]
API uitleg toegevoegd.
