### ISSUE TITLE
Peer review - week 2

### ISSUE THREAD

**Issue by kilroy763** [lars-ruijs/real-time-web-2021#2]
* Readme zit erg goed in elkaar, bevat tot nu toe netjes alles. Goede beschrijving van je concept. Livelink is aanwezig en ook de eerdere concepten.
* Data Lifecycle diagram is erg gedetailleerd en goed te begrijpen ook. Zit mooi in elkaar.
* Code erg netjes opgesplitst in modules en is erg overzichtelijk.

Ziet er allemaal erg goed uit en ik heb er niks op aan te merken. Het enige wat mist is de CSS maar dat is begrijpelijk als je al zoveel tijd in de server / readme hebt gestopt.

**Comment by lars-ruijs** [comment]
CSS styling toegevoegd.
